server {
    listen 80;
    
    # API → FastAPI
    location /api/ {
        proxy_pass http://api:8000/;
    }

    # Static files
    location /static/ {
        alias /usr/share/nginx/html/static/;
    }

    # Root → index.html
    location / {
        try_files $uri /static/index.html;
    }
}
